@ECHO OFF
ECHO ---------------------------------
ECHO Half-Life Studio Model Decompiler
ECHO Version 1.2
ECHO Copyright by Kratisto
ECHO ---------------------------------
ECHO.
ECHO Drag and drop your .mdl file here, after that press Enter:
SET qcfile=
SET /P qcfile=
ECHO.
ECHO ---------------------------------
ECHO 1. Decompile reference model
ECHO 2. Decompile model that need to be fixed
SET mdltype=
SET /P mdltype=Choose your model type: 
mdldec.exe %qcfile%
IF %mdltype% == 2 GOTO :delsmd
PAUSE
EXIT

:delsmd
CD %qcfile%\..
ECHO.
ECHO DEL /F /Qeting unused files...
DEL /F /Q back.smd
DEL /F /Q crouchrun.smd
DEL /F /Q crouch_aim_ak47_blend1.smd
DEL /F /Q crouch_aim_ak47_blend2.smd
DEL /F /Q crouch_aim_ak47_blend3.smd
DEL /F /Q crouch_aim_ak47_blend4.smd
DEL /F /Q crouch_aim_ak47_blend5.smd
DEL /F /Q crouch_aim_ak47_blend6.smd
DEL /F /Q crouch_aim_ak47_blend7.smd
DEL /F /Q crouch_aim_ak47_blend8.smd
DEL /F /Q crouch_aim_ak47_blend9.smd
DEL /F /Q crouch_aim_c4_blend1.smd
DEL /F /Q crouch_aim_c4_blend2.smd
DEL /F /Q crouch_aim_c4_blend3.smd
DEL /F /Q crouch_aim_c4_blend4.smd
DEL /F /Q crouch_aim_c4_blend5.smd
DEL /F /Q crouch_aim_c4_blend6.smd
DEL /F /Q crouch_aim_c4_blend7.smd
DEL /F /Q crouch_aim_c4_blend8.smd
DEL /F /Q crouch_aim_c4_blend9.smd
DEL /F /Q crouch_aim_carbine_blend1.smd
DEL /F /Q crouch_aim_carbine_blend2.smd
DEL /F /Q crouch_aim_carbine_blend3.smd
DEL /F /Q crouch_aim_carbine_blend4.smd
DEL /F /Q crouch_aim_carbine_blend5.smd
DEL /F /Q crouch_aim_carbine_blend6.smd
DEL /F /Q crouch_aim_carbine_blend7.smd
DEL /F /Q crouch_aim_carbine_blend8.smd
DEL /F /Q crouch_aim_carbine_blend9.smd
DEL /F /Q crouch_aim_dualpistols_1_blend1.smd
DEL /F /Q crouch_aim_dualpistols_1_blend2.smd
DEL /F /Q crouch_aim_dualpistols_1_blend3.smd
DEL /F /Q crouch_aim_dualpistols_1_blend4.smd
DEL /F /Q crouch_aim_dualpistols_1_blend5.smd
DEL /F /Q crouch_aim_dualpistols_1_blend6.smd
DEL /F /Q crouch_aim_dualpistols_1_blend7.smd
DEL /F /Q crouch_aim_dualpistols_1_blend8.smd
DEL /F /Q crouch_aim_dualpistols_1_blend9.smd
DEL /F /Q crouch_aim_dualpistols_2_blend1.smd
DEL /F /Q crouch_aim_dualpistols_2_blend2.smd
DEL /F /Q crouch_aim_dualpistols_2_blend3.smd
DEL /F /Q crouch_aim_dualpistols_2_blend4.smd
DEL /F /Q crouch_aim_dualpistols_2_blend5.smd
DEL /F /Q crouch_aim_dualpistols_2_blend6.smd
DEL /F /Q crouch_aim_dualpistols_2_blend7.smd
DEL /F /Q crouch_aim_dualpistols_2_blend8.smd
DEL /F /Q crouch_aim_dualpistols_2_blend9.smd
DEL /F /Q crouch_aim_grenade_blend1.smd
DEL /F /Q crouch_aim_grenade_blend2.smd
DEL /F /Q crouch_aim_grenade_blend3.smd
DEL /F /Q crouch_aim_grenade_blend4.smd
DEL /F /Q crouch_aim_grenade_blend5.smd
DEL /F /Q crouch_aim_grenade_blend6.smd
DEL /F /Q crouch_aim_grenade_blend7.smd
DEL /F /Q crouch_aim_grenade_blend8.smd
DEL /F /Q crouch_aim_grenade_blend9.smd
DEL /F /Q crouch_aim_knife_blend1.smd
DEL /F /Q crouch_aim_knife_blend2.smd
DEL /F /Q crouch_aim_knife_blend3.smd
DEL /F /Q crouch_aim_knife_blend4.smd
DEL /F /Q crouch_aim_knife_blend5.smd
DEL /F /Q crouch_aim_knife_blend6.smd
DEL /F /Q crouch_aim_knife_blend7.smd
DEL /F /Q crouch_aim_knife_blend8.smd
DEL /F /Q crouch_aim_knife_blend9.smd
DEL /F /Q crouch_aim_m249_blend1.smd
DEL /F /Q crouch_aim_m249_blend2.smd
DEL /F /Q crouch_aim_m249_blend3.smd
DEL /F /Q crouch_aim_m249_blend4.smd
DEL /F /Q crouch_aim_m249_blend5.smd
DEL /F /Q crouch_aim_m249_blend6.smd
DEL /F /Q crouch_aim_m249_blend7.smd
DEL /F /Q crouch_aim_m249_blend8.smd
DEL /F /Q crouch_aim_m249_blend9.smd
DEL /F /Q crouch_aim_mp5_blend1.smd
DEL /F /Q crouch_aim_mp5_blend2.smd
DEL /F /Q crouch_aim_mp5_blend3.smd
DEL /F /Q crouch_aim_mp5_blend4.smd
DEL /F /Q crouch_aim_mp5_blend5.smd
DEL /F /Q crouch_aim_mp5_blend6.smd
DEL /F /Q crouch_aim_mp5_blend7.smd
DEL /F /Q crouch_aim_mp5_blend8.smd
DEL /F /Q crouch_aim_mp5_blend9.smd
DEL /F /Q crouch_aim_onehanded_blend1.smd
DEL /F /Q crouch_aim_onehanded_blend2.smd
DEL /F /Q crouch_aim_onehanded_blend3.smd
DEL /F /Q crouch_aim_onehanded_blend4.smd
DEL /F /Q crouch_aim_onehanded_blend5.smd
DEL /F /Q crouch_aim_onehanded_blend6.smd
DEL /F /Q crouch_aim_onehanded_blend7.smd
DEL /F /Q crouch_aim_onehanded_blend8.smd
DEL /F /Q crouch_aim_onehanded_blend9.smd
DEL /F /Q crouch_aim_rifle_blend1.smd
DEL /F /Q crouch_aim_rifle_blend2.smd
DEL /F /Q crouch_aim_rifle_blend3.smd
DEL /F /Q crouch_aim_rifle_blend4.smd
DEL /F /Q crouch_aim_rifle_blend5.smd
DEL /F /Q crouch_aim_rifle_blend6.smd
DEL /F /Q crouch_aim_rifle_blend7.smd
DEL /F /Q crouch_aim_rifle_blend8.smd
DEL /F /Q crouch_aim_rifle_blend9.smd
DEL /F /Q crouch_aim_shielded_blend1.smd
DEL /F /Q crouch_aim_shielded_blend2.smd
DEL /F /Q crouch_aim_shielded_blend3.smd
DEL /F /Q crouch_aim_shielded_blend4.smd
DEL /F /Q crouch_aim_shielded_blend5.smd
DEL /F /Q crouch_aim_shielded_blend6.smd
DEL /F /Q crouch_aim_shielded_blend7.smd
DEL /F /Q crouch_aim_shielded_blend8.smd
DEL /F /Q crouch_aim_shielded_blend9.smd
DEL /F /Q crouch_aim_shieldgren_blend1.smd
DEL /F /Q crouch_aim_shieldgren_blend2.smd
DEL /F /Q crouch_aim_shieldgren_blend3.smd
DEL /F /Q crouch_aim_shieldgren_blend4.smd
DEL /F /Q crouch_aim_shieldgren_blend5.smd
DEL /F /Q crouch_aim_shieldgren_blend6.smd
DEL /F /Q crouch_aim_shieldgren_blend7.smd
DEL /F /Q crouch_aim_shieldgren_blend8.smd
DEL /F /Q crouch_aim_shieldgren_blend9.smd
DEL /F /Q crouch_aim_shieldgun_blend1.smd
DEL /F /Q crouch_aim_shieldgun_blend2.smd
DEL /F /Q crouch_aim_shieldgun_blend3.smd
DEL /F /Q crouch_aim_shieldgun_blend4.smd
DEL /F /Q crouch_aim_shieldgun_blend5.smd
DEL /F /Q crouch_aim_shieldgun_blend6.smd
DEL /F /Q crouch_aim_shieldgun_blend7.smd
DEL /F /Q crouch_aim_shieldgun_blend8.smd
DEL /F /Q crouch_aim_shieldgun_blend9.smd
DEL /F /Q crouch_aim_shieldknife_blend1.smd
DEL /F /Q crouch_aim_shieldknife_blend2.smd
DEL /F /Q crouch_aim_shieldknife_blend3.smd
DEL /F /Q crouch_aim_shieldknife_blend4.smd
DEL /F /Q crouch_aim_shieldknife_blend5.smd
DEL /F /Q crouch_aim_shieldknife_blend6.smd
DEL /F /Q crouch_aim_shieldknife_blend7.smd
DEL /F /Q crouch_aim_shieldknife_blend8.smd
DEL /F /Q crouch_aim_shieldknife_blend9.smd
DEL /F /Q crouch_aim_shotgun_blend1.smd
DEL /F /Q crouch_aim_shotgun_blend2.smd
DEL /F /Q crouch_aim_shotgun_blend3.smd
DEL /F /Q crouch_aim_shotgun_blend4.smd
DEL /F /Q crouch_aim_shotgun_blend5.smd
DEL /F /Q crouch_aim_shotgun_blend6.smd
DEL /F /Q crouch_aim_shotgun_blend7.smd
DEL /F /Q crouch_aim_shotgun_blend8.smd
DEL /F /Q crouch_aim_shotgun_blend9.smd
DEL /F /Q crouch_die.smd
DEL /F /Q crouch_idle.smd
DEL /F /Q crouch_reload_ak47.smd
DEL /F /Q crouch_reload_carbine.smd
DEL /F /Q crouch_reload_dualpistols_1.smd
DEL /F /Q crouch_reload_dualpistols_2.smd
DEL /F /Q crouch_reload_m249.smd
DEL /F /Q crouch_reload_mp5.smd
DEL /F /Q crouch_reload_onehanded.smd
DEL /F /Q crouch_reload_rifle.smd
DEL /F /Q crouch_reload_shieldgun.smd
DEL /F /Q crouch_reload_shotgun.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend1.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend2.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend3.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend4.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend5.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend6.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend7.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend8.smd
DEL /F /Q crouch_shoot2_dualpistols_1_blend9.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend1.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend2.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend3.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend4.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend5.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend6.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend7.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend8.smd
DEL /F /Q crouch_shoot2_dualpistols_2_blend9.smd
DEL /F /Q crouch_shoot_ak47_blend1.smd
DEL /F /Q crouch_shoot_ak47_blend2.smd
DEL /F /Q crouch_shoot_ak47_blend3.smd
DEL /F /Q crouch_shoot_ak47_blend4.smd
DEL /F /Q crouch_shoot_ak47_blend5.smd
DEL /F /Q crouch_shoot_ak47_blend6.smd
DEL /F /Q crouch_shoot_ak47_blend7.smd
DEL /F /Q crouch_shoot_ak47_blend8.smd
DEL /F /Q crouch_shoot_ak47_blend9.smd
DEL /F /Q crouch_shoot_c4.smd
DEL /F /Q crouch_shoot_carbine_blend1.smd
DEL /F /Q crouch_shoot_carbine_blend2.smd
DEL /F /Q crouch_shoot_carbine_blend3.smd
DEL /F /Q crouch_shoot_carbine_blend4.smd
DEL /F /Q crouch_shoot_carbine_blend5.smd
DEL /F /Q crouch_shoot_carbine_blend6.smd
DEL /F /Q crouch_shoot_carbine_blend7.smd
DEL /F /Q crouch_shoot_carbine_blend8.smd
DEL /F /Q crouch_shoot_carbine_blend9.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend1.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend2.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend3.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend4.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend5.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend6.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend7.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend8.smd
DEL /F /Q crouch_shoot_dualpistols_1_blend9.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend1.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend2.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend3.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend4.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend5.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend6.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend7.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend8.smd
DEL /F /Q crouch_shoot_dualpistols_2_blend9.smd
DEL /F /Q crouch_shoot_grenade_blend1.smd
DEL /F /Q crouch_shoot_grenade_blend2.smd
DEL /F /Q crouch_shoot_grenade_blend3.smd
DEL /F /Q crouch_shoot_grenade_blend4.smd
DEL /F /Q crouch_shoot_grenade_blend5.smd
DEL /F /Q crouch_shoot_grenade_blend6.smd
DEL /F /Q crouch_shoot_grenade_blend7.smd
DEL /F /Q crouch_shoot_grenade_blend8.smd
DEL /F /Q crouch_shoot_grenade_blend9.smd
DEL /F /Q crouch_shoot_knife_blend1.smd
DEL /F /Q crouch_shoot_knife_blend2.smd
DEL /F /Q crouch_shoot_knife_blend3.smd
DEL /F /Q crouch_shoot_knife_blend4.smd
DEL /F /Q crouch_shoot_knife_blend5.smd
DEL /F /Q crouch_shoot_knife_blend6.smd
DEL /F /Q crouch_shoot_knife_blend7.smd
DEL /F /Q crouch_shoot_knife_blend8.smd
DEL /F /Q crouch_shoot_knife_blend9.smd
DEL /F /Q crouch_shoot_m249_blend1.smd
DEL /F /Q crouch_shoot_m249_blend2.smd
DEL /F /Q crouch_shoot_m249_blend3.smd
DEL /F /Q crouch_shoot_m249_blend4.smd
DEL /F /Q crouch_shoot_m249_blend5.smd
DEL /F /Q crouch_shoot_m249_blend6.smd
DEL /F /Q crouch_shoot_m249_blend7.smd
DEL /F /Q crouch_shoot_m249_blend8.smd
DEL /F /Q crouch_shoot_m249_blend9.smd
DEL /F /Q crouch_shoot_mp5_blend1.smd
DEL /F /Q crouch_shoot_mp5_blend2.smd
DEL /F /Q crouch_shoot_mp5_blend3.smd
DEL /F /Q crouch_shoot_mp5_blend4.smd
DEL /F /Q crouch_shoot_mp5_blend5.smd
DEL /F /Q crouch_shoot_mp5_blend6.smd
DEL /F /Q crouch_shoot_mp5_blend7.smd
DEL /F /Q crouch_shoot_mp5_blend8.smd
DEL /F /Q crouch_shoot_mp5_blend9.smd
DEL /F /Q crouch_shoot_onehanded_blend1.smd
DEL /F /Q crouch_shoot_onehanded_blend2.smd
DEL /F /Q crouch_shoot_onehanded_blend3.smd
DEL /F /Q crouch_shoot_onehanded_blend4.smd
DEL /F /Q crouch_shoot_onehanded_blend5.smd
DEL /F /Q crouch_shoot_onehanded_blend6.smd
DEL /F /Q crouch_shoot_onehanded_blend7.smd
DEL /F /Q crouch_shoot_onehanded_blend8.smd
DEL /F /Q crouch_shoot_onehanded_blend9.smd
DEL /F /Q crouch_shoot_rifle_blend1.smd
DEL /F /Q crouch_shoot_rifle_blend2.smd
DEL /F /Q crouch_shoot_rifle_blend3.smd
DEL /F /Q crouch_shoot_rifle_blend4.smd
DEL /F /Q crouch_shoot_rifle_blend5.smd
DEL /F /Q crouch_shoot_rifle_blend6.smd
DEL /F /Q crouch_shoot_rifle_blend7.smd
DEL /F /Q crouch_shoot_rifle_blend8.smd
DEL /F /Q crouch_shoot_rifle_blend9.smd
DEL /F /Q crouch_shoot_shieldgren_blend1.smd
DEL /F /Q crouch_shoot_shieldgren_blend2.smd
DEL /F /Q crouch_shoot_shieldgren_blend3.smd
DEL /F /Q crouch_shoot_shieldgren_blend4.smd
DEL /F /Q crouch_shoot_shieldgren_blend5.smd
DEL /F /Q crouch_shoot_shieldgren_blend6.smd
DEL /F /Q crouch_shoot_shieldgren_blend7.smd
DEL /F /Q crouch_shoot_shieldgren_blend8.smd
DEL /F /Q crouch_shoot_shieldgren_blend9.smd
DEL /F /Q crouch_shoot_shieldgun_blend1.smd
DEL /F /Q crouch_shoot_shieldgun_blend2.smd
DEL /F /Q crouch_shoot_shieldgun_blend3.smd
DEL /F /Q crouch_shoot_shieldgun_blend4.smd
DEL /F /Q crouch_shoot_shieldgun_blend5.smd
DEL /F /Q crouch_shoot_shieldgun_blend6.smd
DEL /F /Q crouch_shoot_shieldgun_blend7.smd
DEL /F /Q crouch_shoot_shieldgun_blend8.smd
DEL /F /Q crouch_shoot_shieldgun_blend9.smd
DEL /F /Q crouch_shoot_shieldknife_blend1.smd
DEL /F /Q crouch_shoot_shieldknife_blend2.smd
DEL /F /Q crouch_shoot_shieldknife_blend3.smd
DEL /F /Q crouch_shoot_shieldknife_blend4.smd
DEL /F /Q crouch_shoot_shieldknife_blend5.smd
DEL /F /Q crouch_shoot_shieldknife_blend6.smd
DEL /F /Q crouch_shoot_shieldknife_blend7.smd
DEL /F /Q crouch_shoot_shieldknife_blend8.smd
DEL /F /Q crouch_shoot_shieldknife_blend9.smd
DEL /F /Q crouch_shoot_shotgun_blend1.smd
DEL /F /Q crouch_shoot_shotgun_blend2.smd
DEL /F /Q crouch_shoot_shotgun_blend3.smd
DEL /F /Q crouch_shoot_shotgun_blend4.smd
DEL /F /Q crouch_shoot_shotgun_blend5.smd
DEL /F /Q crouch_shoot_shotgun_blend6.smd
DEL /F /Q crouch_shoot_shotgun_blend7.smd
DEL /F /Q crouch_shoot_shotgun_blend8.smd
DEL /F /Q crouch_shoot_shotgun_blend9.smd
DEL /F /Q death1.smd
DEL /F /Q death2.smd
DEL /F /Q death3.smd
DEL /F /Q dummy.smd
DEL /F /Q forward.smd
DEL /F /Q gutshot.smd
DEL /F /Q gut_flinch_blend1.smd
DEL /F /Q gut_flinch_blend2.smd
DEL /F /Q gut_flinch_blend3.smd
DEL /F /Q gut_flinch_blend4.smd
DEL /F /Q gut_flinch_blend5.smd
DEL /F /Q gut_flinch_blend6.smd
DEL /F /Q gut_flinch_blend7.smd
DEL /F /Q gut_flinch_blend8.smd
DEL /F /Q gut_flinch_blend9.smd
DEL /F /Q head.smd
DEL /F /Q head_flinch_blend1.smd
DEL /F /Q head_flinch_blend2.smd
DEL /F /Q head_flinch_blend3.smd
DEL /F /Q head_flinch_blend4.smd
DEL /F /Q head_flinch_blend5.smd
DEL /F /Q head_flinch_blend6.smd
DEL /F /Q head_flinch_blend7.smd
DEL /F /Q head_flinch_blend8.smd
DEL /F /Q head_flinch_blend9.smd
DEL /F /Q idle1.smd
DEL /F /Q I_am_a_stupid_placeholder.smd
DEL /F /Q jump.smd
DEL /F /Q left.smd
DEL /F /Q longjump.smd
DEL /F /Q ref_aim_ak47_blend1.smd
DEL /F /Q ref_aim_ak47_blend2.smd
DEL /F /Q ref_aim_ak47_blend3.smd
DEL /F /Q ref_aim_ak47_blend4.smd
DEL /F /Q ref_aim_ak47_blend5.smd
DEL /F /Q ref_aim_ak47_blend6.smd
DEL /F /Q ref_aim_ak47_blend7.smd
DEL /F /Q ref_aim_ak47_blend8.smd
DEL /F /Q ref_aim_ak47_blend9.smd
DEL /F /Q ref_aim_c4_blend1.smd
DEL /F /Q ref_aim_c4_blend2.smd
DEL /F /Q ref_aim_c4_blend3.smd
DEL /F /Q ref_aim_c4_blend4.smd
DEL /F /Q ref_aim_c4_blend5.smd
DEL /F /Q ref_aim_c4_blend6.smd
DEL /F /Q ref_aim_c4_blend7.smd
DEL /F /Q ref_aim_c4_blend8.smd
DEL /F /Q ref_aim_c4_blend9.smd
DEL /F /Q ref_aim_carbine_blend1.smd
DEL /F /Q ref_aim_carbine_blend2.smd
DEL /F /Q ref_aim_carbine_blend3.smd
DEL /F /Q ref_aim_carbine_blend4.smd
DEL /F /Q ref_aim_carbine_blend5.smd
DEL /F /Q ref_aim_carbine_blend6.smd
DEL /F /Q ref_aim_carbine_blend7.smd
DEL /F /Q ref_aim_carbine_blend8.smd
DEL /F /Q ref_aim_carbine_blend9.smd
DEL /F /Q ref_aim_dualpistols_1_blend1.smd
DEL /F /Q ref_aim_dualpistols_1_blend2.smd
DEL /F /Q ref_aim_dualpistols_1_blend3.smd
DEL /F /Q ref_aim_dualpistols_1_blend4.smd
DEL /F /Q ref_aim_dualpistols_1_blend5.smd
DEL /F /Q ref_aim_dualpistols_1_blend6.smd
DEL /F /Q ref_aim_dualpistols_1_blend7.smd
DEL /F /Q ref_aim_dualpistols_1_blend8.smd
DEL /F /Q ref_aim_dualpistols_1_blend9.smd
DEL /F /Q ref_aim_dualpistols_2_blend1.smd
DEL /F /Q ref_aim_dualpistols_2_blend2.smd
DEL /F /Q ref_aim_dualpistols_2_blend3.smd
DEL /F /Q ref_aim_dualpistols_2_blend4.smd
DEL /F /Q ref_aim_dualpistols_2_blend5.smd
DEL /F /Q ref_aim_dualpistols_2_blend6.smd
DEL /F /Q ref_aim_dualpistols_2_blend7.smd
DEL /F /Q ref_aim_dualpistols_2_blend8.smd
DEL /F /Q ref_aim_dualpistols_2_blend9.smd
DEL /F /Q ref_aim_grenade_blend1.smd
DEL /F /Q ref_aim_grenade_blend2.smd
DEL /F /Q ref_aim_grenade_blend3.smd
DEL /F /Q ref_aim_grenade_blend4.smd
DEL /F /Q ref_aim_grenade_blend5.smd
DEL /F /Q ref_aim_grenade_blend6.smd
DEL /F /Q ref_aim_grenade_blend7.smd
DEL /F /Q ref_aim_grenade_blend8.smd
DEL /F /Q ref_aim_grenade_blend9.smd
DEL /F /Q ref_aim_knife_blend1.smd
DEL /F /Q ref_aim_knife_blend2.smd
DEL /F /Q ref_aim_knife_blend3.smd
DEL /F /Q ref_aim_knife_blend4.smd
DEL /F /Q ref_aim_knife_blend5.smd
DEL /F /Q ref_aim_knife_blend6.smd
DEL /F /Q ref_aim_knife_blend7.smd
DEL /F /Q ref_aim_knife_blend8.smd
DEL /F /Q ref_aim_knife_blend9.smd
DEL /F /Q ref_aim_m249_blend1.smd
DEL /F /Q ref_aim_m249_blend2.smd
DEL /F /Q ref_aim_m249_blend3.smd
DEL /F /Q ref_aim_m249_blend4.smd
DEL /F /Q ref_aim_m249_blend5.smd
DEL /F /Q ref_aim_m249_blend6.smd
DEL /F /Q ref_aim_m249_blend7.smd
DEL /F /Q ref_aim_m249_blend8.smd
DEL /F /Q ref_aim_m249_blend9.smd
DEL /F /Q ref_aim_mp5_blend1.smd
DEL /F /Q ref_aim_mp5_blend2.smd
DEL /F /Q ref_aim_mp5_blend3.smd
DEL /F /Q ref_aim_mp5_blend4.smd
DEL /F /Q ref_aim_mp5_blend5.smd
DEL /F /Q ref_aim_mp5_blend6.smd
DEL /F /Q ref_aim_mp5_blend7.smd
DEL /F /Q ref_aim_mp5_blend8.smd
DEL /F /Q ref_aim_mp5_blend9.smd
DEL /F /Q ref_aim_onehanded_blend1.smd
DEL /F /Q ref_aim_onehanded_blend2.smd
DEL /F /Q ref_aim_onehanded_blend3.smd
DEL /F /Q ref_aim_onehanded_blend4.smd
DEL /F /Q ref_aim_onehanded_blend5.smd
DEL /F /Q ref_aim_onehanded_blend6.smd
DEL /F /Q ref_aim_onehanded_blend7.smd
DEL /F /Q ref_aim_onehanded_blend8.smd
DEL /F /Q ref_aim_onehanded_blend9.smd
DEL /F /Q ref_aim_rifle_blend1.smd
DEL /F /Q ref_aim_rifle_blend2.smd
DEL /F /Q ref_aim_rifle_blend3.smd
DEL /F /Q ref_aim_rifle_blend4.smd
DEL /F /Q ref_aim_rifle_blend5.smd
DEL /F /Q ref_aim_rifle_blend6.smd
DEL /F /Q ref_aim_rifle_blend7.smd
DEL /F /Q ref_aim_rifle_blend8.smd
DEL /F /Q ref_aim_rifle_blend9.smd
DEL /F /Q ref_aim_shielded_blend1.smd
DEL /F /Q ref_aim_shielded_blend2.smd
DEL /F /Q ref_aim_shielded_blend3.smd
DEL /F /Q ref_aim_shielded_blend4.smd
DEL /F /Q ref_aim_shielded_blend5.smd
DEL /F /Q ref_aim_shielded_blend6.smd
DEL /F /Q ref_aim_shielded_blend7.smd
DEL /F /Q ref_aim_shielded_blend8.smd
DEL /F /Q ref_aim_shielded_blend9.smd
DEL /F /Q ref_aim_shieldgren_blend1.smd
DEL /F /Q ref_aim_shieldgren_blend2.smd
DEL /F /Q ref_aim_shieldgren_blend3.smd
DEL /F /Q ref_aim_shieldgren_blend4.smd
DEL /F /Q ref_aim_shieldgren_blend5.smd
DEL /F /Q ref_aim_shieldgren_blend6.smd
DEL /F /Q ref_aim_shieldgren_blend7.smd
DEL /F /Q ref_aim_shieldgren_blend8.smd
DEL /F /Q ref_aim_shieldgren_blend9.smd
DEL /F /Q ref_aim_shieldgun_blend1.smd
DEL /F /Q ref_aim_shieldgun_blend2.smd
DEL /F /Q ref_aim_shieldgun_blend3.smd
DEL /F /Q ref_aim_shieldgun_blend4.smd
DEL /F /Q ref_aim_shieldgun_blend5.smd
DEL /F /Q ref_aim_shieldgun_blend6.smd
DEL /F /Q ref_aim_shieldgun_blend7.smd
DEL /F /Q ref_aim_shieldgun_blend8.smd
DEL /F /Q ref_aim_shieldgun_blend9.smd
DEL /F /Q ref_aim_shieldknife_blend1.smd
DEL /F /Q ref_aim_shieldknife_blend2.smd
DEL /F /Q ref_aim_shieldknife_blend3.smd
DEL /F /Q ref_aim_shieldknife_blend4.smd
DEL /F /Q ref_aim_shieldknife_blend5.smd
DEL /F /Q ref_aim_shieldknife_blend6.smd
DEL /F /Q ref_aim_shieldknife_blend7.smd
DEL /F /Q ref_aim_shieldknife_blend8.smd
DEL /F /Q ref_aim_shieldknife_blend9.smd
DEL /F /Q ref_aim_shotgun_blend1.smd
DEL /F /Q ref_aim_shotgun_blend2.smd
DEL /F /Q ref_aim_shotgun_blend3.smd
DEL /F /Q ref_aim_shotgun_blend4.smd
DEL /F /Q ref_aim_shotgun_blend5.smd
DEL /F /Q ref_aim_shotgun_blend6.smd
DEL /F /Q ref_aim_shotgun_blend7.smd
DEL /F /Q ref_aim_shotgun_blend8.smd
DEL /F /Q ref_aim_shotgun_blend9.smd
DEL /F /Q ref_reload_ak47.smd
DEL /F /Q ref_reload_c4.smd
DEL /F /Q ref_reload_carbine.smd
DEL /F /Q ref_reload_dualpistols_1.smd
DEL /F /Q ref_reload_dualpistols_2.smd
DEL /F /Q ref_reload_m249.smd
DEL /F /Q ref_reload_mp5.smd
DEL /F /Q ref_reload_onehanded.smd
DEL /F /Q ref_reload_rifle.smd
DEL /F /Q ref_reload_shieldgun.smd
DEL /F /Q ref_reload_shotgun.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend1.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend2.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend3.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend4.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend5.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend6.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend7.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend8.smd
DEL /F /Q ref_shoot2_dualpistols_1_blend9.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend1.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend2.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend3.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend4.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend5.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend6.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend7.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend8.smd
DEL /F /Q ref_shoot2_dualpistols_2_blend9.smd
DEL /F /Q ref_shoot_ak47_blend1.smd
DEL /F /Q ref_shoot_ak47_blend2.smd
DEL /F /Q ref_shoot_ak47_blend3.smd
DEL /F /Q ref_shoot_ak47_blend4.smd
DEL /F /Q ref_shoot_ak47_blend5.smd
DEL /F /Q ref_shoot_ak47_blend6.smd
DEL /F /Q ref_shoot_ak47_blend7.smd
DEL /F /Q ref_shoot_ak47_blend8.smd
DEL /F /Q ref_shoot_ak47_blend9.smd
DEL /F /Q ref_shoot_c4.smd
DEL /F /Q ref_shoot_carbine_blend1.smd
DEL /F /Q ref_shoot_carbine_blend2.smd
DEL /F /Q ref_shoot_carbine_blend3.smd
DEL /F /Q ref_shoot_carbine_blend4.smd
DEL /F /Q ref_shoot_carbine_blend5.smd
DEL /F /Q ref_shoot_carbine_blend6.smd
DEL /F /Q ref_shoot_carbine_blend7.smd
DEL /F /Q ref_shoot_carbine_blend8.smd
DEL /F /Q ref_shoot_carbine_blend9.smd
DEL /F /Q ref_shoot_dualpistols_1_blend1.smd
DEL /F /Q ref_shoot_dualpistols_1_blend2.smd
DEL /F /Q ref_shoot_dualpistols_1_blend3.smd
DEL /F /Q ref_shoot_dualpistols_1_blend4.smd
DEL /F /Q ref_shoot_dualpistols_1_blend5.smd
DEL /F /Q ref_shoot_dualpistols_1_blend6.smd
DEL /F /Q ref_shoot_dualpistols_1_blend7.smd
DEL /F /Q ref_shoot_dualpistols_1_blend8.smd
DEL /F /Q ref_shoot_dualpistols_1_blend9.smd
DEL /F /Q ref_shoot_dualpistols_2_blend1.smd
DEL /F /Q ref_shoot_dualpistols_2_blend2.smd
DEL /F /Q ref_shoot_dualpistols_2_blend3.smd
DEL /F /Q ref_shoot_dualpistols_2_blend4.smd
DEL /F /Q ref_shoot_dualpistols_2_blend5.smd
DEL /F /Q ref_shoot_dualpistols_2_blend6.smd
DEL /F /Q ref_shoot_dualpistols_2_blend7.smd
DEL /F /Q ref_shoot_dualpistols_2_blend8.smd
DEL /F /Q ref_shoot_dualpistols_2_blend9.smd
DEL /F /Q ref_shoot_grenade_blend1.smd
DEL /F /Q ref_shoot_grenade_blend2.smd
DEL /F /Q ref_shoot_grenade_blend3.smd
DEL /F /Q ref_shoot_grenade_blend4.smd
DEL /F /Q ref_shoot_grenade_blend5.smd
DEL /F /Q ref_shoot_grenade_blend6.smd
DEL /F /Q ref_shoot_grenade_blend7.smd
DEL /F /Q ref_shoot_grenade_blend8.smd
DEL /F /Q ref_shoot_grenade_blend9.smd
DEL /F /Q ref_shoot_knife_blend1.smd
DEL /F /Q ref_shoot_knife_blend2.smd
DEL /F /Q ref_shoot_knife_blend3.smd
DEL /F /Q ref_shoot_knife_blend4.smd
DEL /F /Q ref_shoot_knife_blend5.smd
DEL /F /Q ref_shoot_knife_blend6.smd
DEL /F /Q ref_shoot_knife_blend7.smd
DEL /F /Q ref_shoot_knife_blend8.smd
DEL /F /Q ref_shoot_knife_blend9.smd
DEL /F /Q ref_shoot_m249_blend1.smd
DEL /F /Q ref_shoot_m249_blend2.smd
DEL /F /Q ref_shoot_m249_blend3.smd
DEL /F /Q ref_shoot_m249_blend4.smd
DEL /F /Q ref_shoot_m249_blend5.smd
DEL /F /Q ref_shoot_m249_blend6.smd
DEL /F /Q ref_shoot_m249_blend7.smd
DEL /F /Q ref_shoot_m249_blend8.smd
DEL /F /Q ref_shoot_m249_blend9.smd
DEL /F /Q ref_shoot_mp5_blend1.smd
DEL /F /Q ref_shoot_mp5_blend2.smd
DEL /F /Q ref_shoot_mp5_blend3.smd
DEL /F /Q ref_shoot_mp5_blend4.smd
DEL /F /Q ref_shoot_mp5_blend5.smd
DEL /F /Q ref_shoot_mp5_blend6.smd
DEL /F /Q ref_shoot_mp5_blend7.smd
DEL /F /Q ref_shoot_mp5_blend8.smd
DEL /F /Q ref_shoot_mp5_blend9.smd
DEL /F /Q ref_shoot_onehanded_blend1.smd
DEL /F /Q ref_shoot_onehanded_blend2.smd
DEL /F /Q ref_shoot_onehanded_blend3.smd
DEL /F /Q ref_shoot_onehanded_blend4.smd
DEL /F /Q ref_shoot_onehanded_blend5.smd
DEL /F /Q ref_shoot_onehanded_blend6.smd
DEL /F /Q ref_shoot_onehanded_blend7.smd
DEL /F /Q ref_shoot_onehanded_blend8.smd
DEL /F /Q ref_shoot_onehanded_blend9.smd
DEL /F /Q ref_shoot_rifle_blend1.smd
DEL /F /Q ref_shoot_rifle_blend2.smd
DEL /F /Q ref_shoot_rifle_blend3.smd
DEL /F /Q ref_shoot_rifle_blend4.smd
DEL /F /Q ref_shoot_rifle_blend5.smd
DEL /F /Q ref_shoot_rifle_blend6.smd
DEL /F /Q ref_shoot_rifle_blend7.smd
DEL /F /Q ref_shoot_rifle_blend8.smd
DEL /F /Q ref_shoot_rifle_blend9.smd
DEL /F /Q ref_shoot_shieldgren_blend1.smd
DEL /F /Q ref_shoot_shieldgren_blend2.smd
DEL /F /Q ref_shoot_shieldgren_blend3.smd
DEL /F /Q ref_shoot_shieldgren_blend4.smd
DEL /F /Q ref_shoot_shieldgren_blend5.smd
DEL /F /Q ref_shoot_shieldgren_blend6.smd
DEL /F /Q ref_shoot_shieldgren_blend7.smd
DEL /F /Q ref_shoot_shieldgren_blend8.smd
DEL /F /Q ref_shoot_shieldgren_blend9.smd
DEL /F /Q ref_shoot_shieldgun_blend1.smd
DEL /F /Q ref_shoot_shieldgun_blend2.smd
DEL /F /Q ref_shoot_shieldgun_blend3.smd
DEL /F /Q ref_shoot_shieldgun_blend4.smd
DEL /F /Q ref_shoot_shieldgun_blend5.smd
DEL /F /Q ref_shoot_shieldgun_blend6.smd
DEL /F /Q ref_shoot_shieldgun_blend7.smd
DEL /F /Q ref_shoot_shieldgun_blend8.smd
DEL /F /Q ref_shoot_shieldgun_blend9.smd
DEL /F /Q ref_shoot_shieldknife_blend1.smd
DEL /F /Q ref_shoot_shieldknife_blend2.smd
DEL /F /Q ref_shoot_shieldknife_blend3.smd
DEL /F /Q ref_shoot_shieldknife_blend4.smd
DEL /F /Q ref_shoot_shieldknife_blend5.smd
DEL /F /Q ref_shoot_shieldknife_blend6.smd
DEL /F /Q ref_shoot_shieldknife_blend7.smd
DEL /F /Q ref_shoot_shieldknife_blend8.smd
DEL /F /Q ref_shoot_shieldknife_blend9.smd
DEL /F /Q ref_shoot_shotgun_blend1.smd
DEL /F /Q ref_shoot_shotgun_blend2.smd
DEL /F /Q ref_shoot_shotgun_blend3.smd
DEL /F /Q ref_shoot_shotgun_blend4.smd
DEL /F /Q ref_shoot_shotgun_blend5.smd
DEL /F /Q ref_shoot_shotgun_blend6.smd
DEL /F /Q ref_shoot_shotgun_blend7.smd
DEL /F /Q ref_shoot_shotgun_blend8.smd
DEL /F /Q ref_shoot_shotgun_blend9.smd
DEL /F /Q right.smd
DEL /F /Q run.smd
DEL /F /Q so_am_I.smd
DEL /F /Q swim.smd
DEL /F /Q treadwater.smd
DEL /F /Q walk.smd
PAUSE 
EXIT