#if defined _crxknives_const_included
    #endinput
#endif

#define _crxknives_const_included

/**
 * Default knife models
 */
#define CRXKNIVES_DEFAULT_V "models/v_knife.mdl"
#define CRXKNIVES_DEFAULT_P "models/p_knife.mdl"

/**
 * Maximum buffer length for knife sounds
 */
const CRXKNIVES_MAX_SOUND_LENGTH = 128

/**
 * Maximum buffer length for select messages
 */
const CRXKNIVES_MAX_MESSAGE_LENGTH = 128

/**
 * Maximum buffer length for attribute values
 */
const CRXKNIVES_MAX_ATTRIBUTE_LENGTH = 64