maps/aim_silentnight.nav
models/hostage.mdl
models/aim_silentnight/zombie.mdl
models/aim_silentnight/zombiet.mdl
overviews/aim_silentnight.bmp
overviews/aim_silentnight.txt
sound/aim_silentnight/arcticwind4.wav
sound/aim_silentnight/drips.wav
sound/aim_silentnight/light_hum.wav
sound/aim_silentnight/lv_neon.wav
sound/aim_silentnight/squirm2.wav
sound/aim_silentnight/thunderclap.wav
sound/aim_silentnight/trailer_wndinsidepark_loop.wav
sound/aim_silentnight/tv_static1.wav
sound/clang_converted.wav