gfx/env/siv2bk.tga
gfx/env/siv2dn.tga
gfx/env/siv2ft.tga
gfx/env/siv2lf.tga
gfx/env/siv2rt.tga
gfx/env/siv2up.tga

maps/cs_evian.nav
maps/cs_evian.res

models/cs_evian/hostage_bloody.mdl
models/cs_evian/hostage_skeleton.mdl
models/cs_evian/hostage_slender.mdl
models/cs_evian/hostage_zombie.mdl

models/cs_evian/props/ac_large.mdl
models/cs_evian/props/atm.mdl
models/cs_evian/props/awning_cafe.mdl
models/cs_evian/props/barrel_blue.mdl
models/cs_evian/props/barrel_brown.mdl
models/cs_evian/props/barrel_metal.mdl
models/cs_evian/props/barrel_orange.mdl
models/cs_evian/props/bicycle.mdl
models/cs_evian/props/cadaver-open.mdl
models/cs_evian/props/cafe.mdl
models/cs_evian/props/car.mdl
models/cs_evian/props/car_dealers.mdl
models/cs_evian/props/chair_cafe.mdl
models/cs_evian/props/electrical_box-closed.mdl
models/cs_evian/props/gign_van.mdl
models/cs_evian/props/horror_spider.mdl
models/cs_evian/props/lamp_interior_wall.mdl
models/cs_evian/props/lamp_mur.mdl
models/cs_evian/props/lamp_socle.mdl
models/cs_evian/props/lamp_street-tall.mdl
models/cs_evian/props/lamp_table.mdl
models/cs_evian/props/pentagram.mdl
models/cs_evian/props/portrait1.mdl
models/cs_evian/props/portrait2.mdl
models/cs_evian/props/portrait3.mdl
models/cs_evian/props/portrait4.mdl
models/cs_evian/props/portrait5.mdl
models/cs_evian/props/portrait6.mdl
models/cs_evian/props/portrait7.mdl
models/cs_evian/props/pumpkin1.mdl
models/cs_evian/props/pumpkin2.mdl
models/cs_evian/props/pumpkin3.mdl
models/cs_evian/props/scary_piano.mdl
models/cs_evian/props/skull.mdl
models/cs_evian/props/table_cafe.mdl
models/cs_evian/props/table_cafe-wreck.mdl
models/cs_evian/props/table_lab-metaltop.mdl
models/cs_evian/props/trash.mdl
models/cs_evian/props/trash_02.mdl
models/cs_evian/props/trash_trashcan.mdl
models/cs_evian/props/truck_large-green.mdl
models/cs_evian/props/truck_old.mdl
models/cs_evian/props/umbrella_cafe.mdl

overviews/cs_evian.bmp
overviews/cs_evian.txt

sound/cs_evian/ambience_night.wav
sound/cs_evian/generator.wav
sound/cs_evian/horror_house_ambience.wav
sound/cs_evian/night_horror.wav
sound/cs_evian/vampire_killer_piano.wav