// cs_mansion_dead.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (78):
gfx/env/hellbk.tga
gfx/env/helldn.tga
gfx/env/hellft.tga
gfx/env/helllf.tga
gfx/env/hellrt.tga
gfx/env/hellup.tga
models/hostage.mdl
models/mam6a/mansion_dead/AF_furnitures_couch_big03.mdl
models/mam6a/mansion_dead/badkarne1.mdl
models/mam6a/mansion_dead/bush05.mdl
models/mam6a/mansion_dead/Bush_Dead_Fall_SM.mdl
models/mam6a/mansion_dead/buzzer_tree.mdl
models/mam6a/mansion_dead/candle1_1.mdl
models/mam6a/mansion_dead/candle_2.mdl
models/mam6a/mansion_dead/candle_2_1.mdl
models/mam6a/mansion_dead/candle_2_2.mdl
models/mam6a/mansion_dead/candle_3.mdl
models/mam6a/mansion_dead/cc_grass.mdl
models/mam6a/mansion_dead/crow.mdl
models/mam6a/mansion_dead/d_2msoffa.mdl
models/mam6a/mansion_dead/doll01.mdl
models/mam6a/mansion_dead/e1bookbig.mdl
models/mam6a/mansion_dead/e1pages2.mdl
models/mam6a/mansion_dead/enima_podsolnuh.mdl
models/mam6a/mansion_dead/fleshgibs.mdl
models/mam6a/mansion_dead/gate_church.mdl
models/mam6a/mansion_dead/got_BracketLamp01.mdl
models/mam6a/mansion_dead/got_Fireplace03.mdl
models/mam6a/mansion_dead/grass_pack3.mdl
models/mam6a/mansion_dead/hessi_baum5.mdl
models/mam6a/mansion_dead/lag_oaktree.mdl
models/mam6a/mansion_dead/pentagram.mdl
models/mam6a/mansion_dead/pepsi_candle.mdl
models/mam6a/mansion_dead/roach111.mdl
models/mam6a/mansion_dead/rotfish.mdl
models/mam6a/mansion_dead/see_derewo.mdl
models/mam6a/mansion_dead/tree_noleaves.mdl
models/mam6a/mansion_dead/wl.mdl
sound/mam6a/mansion_Deat/allgoing.wav
sound/mam6a/mansion_Deat/bdclose1.wav
sound/mam6a/mansion_Deat/bear1.wav
sound/mam6a/mansion_Deat/Birds5.wav
sound/mam6a/mansion_Deat/brass_bell_C.wav
sound/mam6a/mansion_Deat/chtotoebanulo2.wav
sound/mam6a/mansion_Deat/CNTAMB.wav
sound/mam6a/mansion_Deat/CricketQuiet.wav
sound/mam6a/mansion_Deat/crow.wav
sound/mam6a/mansion_Deat/debris8.wav
sound/mam6a/mansion_Deat/dog4.wav
sound/mam6a/mansion_Deat/firefx7.wav
sound/mam6a/mansion_Deat/grass.wav
sound/mam6a/mansion_Deat/load_drips.wav
sound/mam6a/mansion_Deat/metall_sfx11.wav
sound/mam6a/mansion_Deat/metall_sfx2.wav
sound/mam6a/mansion_Deat/naturebirds.wav
sound/mam6a/mansion_Deat/rain_inside_loop.wav
sound/mam6a/mansion_Deat/random_metal.wav
sound/mam6a/mansion_Deat/schrei.wav
sound/mam6a/mansion_Deat/Scream.wav
sound/mam6a/mansion_Deat/screamer.wav
sound/mam6a/mansion_Deat/siren_scream.wav
sound/mam6a/mansion_Deat/skrimer.wav
sound/mam6a/mansion_Deat/squeak1.wav
sound/mam6a/mansion_Deat/thunder_clap.wav
sound/mam6a/mansion_Deat/underwaterbubble1.wav
sound/mam6a/mansion_Deat/usham_pizda.wav
sound/mam6a/mansion_Deat/warnyou.wav
sound/mam6a/mansion_Deat/wolfhowl01.wav
sound/mam6a/mansion_Deat/wolfhowl02.wav
sound/mam6a/mansion_Deat/wood_sfx2.wav
sound/mam6a/mansion_Deat/wood_sfx3.wav
sound/mam6a/mansion_Deat/wood_sfx4.wav
sprites/gbcontest/spotlight309.spr
sprites/mam6a/m_d/fire3.spr
sprites/mam6a/m_d/firefire.spr
sprites/mam6a/m_d/lgtning.spr
sprites/mam6a/m_d/moonmj.spr
sprites/mam6a/m_d/Particles01.spr
