gfx/env/cs_manoirup.tga
gfx/env/cs_manoirdn.tga
gfx/env/cs_manoirlf.tga
gfx/env/cs_manoirrt.tga
gfx/env/cs_manoirft.tga
gfx/env/cs_manoirbk.tga
gfx/palette.lmp
sprites/cs_manoir/glow01.spr
models/cs_manoir/arc_fern.mdl
models/cs_manoir/arc_flower.mdl
models/cs_manoir/arc_xer_tree2.mdl
models/cs_manoir/cadaver.mdl
models/cs_manoir/csouris.mdl
models/cs_manoir/dinner_table2.mdl
models/cs_manoir/tablelamp.mdl
models/cs_manoir/garbre.mdl
models/cs_manoir/grandfather_clock1.mdl
models/cs_manoir/lamp.mdl
models/cs_manoir/pc.mdl
models/cs_manoir/pine_tree.mdl
models/cs_manoir/vbanc.mdl
models/cs_manoir/w_rpg.mdl
models/cs_manoir/w_rpgt.mdl
maps/cs_manoir.bsp
maps/cs_manoir.txt
overviews/cs_manoir.bmp
overviews/cs_manoir.txt
sound/cs_manoir/birdsnight.wav
sound/cs_manoir/cat1.wav
sound/cs_manoir/chouette1.wav
sound/cs_manoir/chouette2.wav
sound/cs_manoir/clock-tick1.wav
sound/cs_manoir/comtoise_balancier.wav
sound/cs_manoir/creackingwood.wav
sound/cs_manoir/firechimney.wav
sound/cs_manoir/grass.wav
sound/cs_manoir/horloge.wav
sound/cs_manoir/maindoors.wav
sound/cs_manoir/piano.wav
sound/cs_manoir/thunderrumble1.wav
sound/cs_manoir/thunderrumble2.wav
sound/cs_manoir/thunderrumble3.wav
sound/cs_manoir/thunderrumble4.wav
sound/cs_manoir/ticking.wav
sound/cs_manoir/wind.wav
sound/cs_manoir/wolfhowl01.wav