//////////////////////////////////////////////////////////
// Resources file, created with 17buddies php script!!! //
// © Chapo 2005-2007 - Infos @ http://www.17buddies.net //
//          More than 15000 maps to download!           //
//                                                      //
//      Can you play all of our maps ?? Sure not!!      //
//////////////////////////////////////////////////////////
//
// Res file generated by mikado for 17Buddies.
//
// Map Name  : cs_rhs22
//
// Download @: http://dwl.17buddies.net/link/map/9725/cs_rhs22.html
//
//////////////////////////////////////////////////////////
gfx/env/52h03up.tga
gfx/env/52h03dn.tga
gfx/env/52h03lf.tga
gfx/env/52h03rt.tga
gfx/env/52h03ft.tga
gfx/env/52h03bk.tga

models/custom_tnoh/arc_bush.mdl
models/custom_tnoh/bed_empty-wood.mdl
models/custom_tnoh/bord.mdl
models/custom_tnoh/bulb.mdl
models/custom_tnoh/dg_chandelier_body.mdl
models/custom_tnoh/dg_chandelier_lamps.mdl
models/custom_tnoh/dg_hostage.mdl
models/custom_tnoh/dg_hostage01.mdl
models/custom_tnoh/dg_hostage01.mdl
models/custom_tnoh/dg_hostage02.mdl
models/custom_tnoh/dg_hostage03.mdl
models/custom_tnoh/dg_hostage04.mdl
models/custom_tnoh/dg_hostage05.mdl
models/custom_tnoh/dg_hostage06.mdl
models/custom_tnoh/dg_hostage07.mdl
models/custom_tnoh/dg_hostage08.mdl
models/custom_tnoh/dg_lamp.mdl
models/custom_tnoh/dg_lamp2_body.mdl
models/custom_tnoh/dg_lamp2_lamp.mdl
models/custom_tnoh/flo_light.mdl
models/custom_tnoh/hono.mdl
models/custom_tnoh/hostage.mdl
models/custom_tnoh/laski_hossu.mdl
models/custom_tnoh/laski_hossu01.mdl 
models/custom_tnoh/laski_hossu02.mdl
models/custom_tnoh/laski_hossu03.mdl
models/custom_tnoh/laski_hossu04.mdl
models/custom_tnoh/laski_hossu05.mdl
models/custom_tnoh/laski_hossu06.mdl
models/custom_tnoh/laski_hossu07.mdl
models/custom_tnoh/laski_hossu08.mdl
models/custom_tnoh/mattress_wreck.mdl
models/custom_tnoh/skeleton.mdl
models/custom_tnoh/vsghost.mdl
models/custom_tnoh/zalec_2bulb2wire.mdl
models/custom_tnoh/piranesitrees/pi_tree.mdl
models/custom_tnoh/piranesitrees/pi_tree1.mdl
models/custom_tnoh/piranesitrees/pi_treeb.mdl
models/custom_tnoh/doenerking/couch3.mdl
models/custom_tnoh/doenerking/tablelamp.mdl
models/custom_tnoh/doenerking/klo.mdl
models/custom_tnoh/doenerking/washbowl.mdl
models/custom_tnoh/doenerking/piano.mdl
models/custom_tnoh/doenerking/vase.mdl

sound/buttons/latchunlocked1.wav
sound/cs_rhs22/clock-tic.wav
sound/cs_rhs22/windy.wav
sound/cs_rhs22/ambient_summer.wav
sound/cs_rhs22/th_scary1.wav
sound/cs_rhs22/th_scary2.wav
sound/cs_rhs22/creak.wav
sound/cs_rhs22/pollo.wav
sound/cs_rhs22/sus.wav
sound/cs_rhs22/th_swing.wav
sound/cs_rhs22/th_boy1.wav
sound/cs_rhs22/th_demon.wav
sound/cs_rhs22/kh_bemel.wav
sound/cs_rhs22/th_demon2.wav 
sound/cs_rhs22/bell.wav
sound/cs_rhs22/scream1.wav
sound/cs_rhs22/asylum.wav
sound/cs_rhs22/growl.wav
sound/cs_rhs22/ghost-short.wav

sprites/glow03.spr
sprites/glow01.spr





overviews/cs_rhs22.txt
overviews/cs_rhs22.bmp
