// cs_xmas_house.res - created with RESGen v2.0 BETA 3.
// RESGen is made by Jeroen "ShadowLord" Bogers.
// For more info go to http://resgen.hltools.com
// or E-mail me at resgen@hltools.com.

// .res entries (71):
gfx/env/siv3up.tga
gfx/env/siv3dn.tga
gfx/env/siv3lf.tga
gfx/env/siv3rt.tga
gfx/env/siv3ft.tga
gfx/env/siv3bk.tga
models/cs_xmas_house/logpile_snow.mdl
models/cs_xmas_house/cc_rack.mdl
models/cs_xmas_house/banquet_table01.mdl
models/cs_xmas_house/chair2.mdl
models/cs_xmas_house/jrx_kitchen.mdl
models/cs_xmas_house/antenna1.mdl
models/cs_xmas_house/xmas_parasha.mdl
models/cs_xmas_house/jrx_sink.mdl
models/cs_xmas_house/cc_footwear_01.mdl
models/cs_xmas_house/cc_footwear_07.mdl
models/cs_xmas_house/cc_footwear_12.mdl
models/cs_xmas_house/got_platter02full.mdl
models/cs_xmas_house/health01.mdl
models/cs_xmas_house/got_fruitcup01.mdl
models/cs_xmas_house/health02.mdl
models/cs_xmas_house/bottle5.mdl
models/cs_xmas_house/xmas_buhlo.mdl
models/cs_xmas_house/fortaklampa.mdl
models/cs_xmas_house/xmas_tumba01.mdl
models/cs_xmas_house/cc_ancabinet_a.mdl
models/cs_xmas_house/xmas_elb.mdl
sprites/cs_xmas_house/flamez.spr
models/cs_xmas_house/fireplace_logs1.mdl
sound/cs_xmas_house/fire.wav
models/cs_xmas_house/refrigerator.mdl
sound/cs_xmas_house/doorbell.wav
sound/cs_xmas_house/flush.wav
models/cs_xmas_house/maniak_table.mdl
models/cs_xmas_house/cannabis.mdl
models/cs_xmas_house/jb_japanese_bed.mdl
models/cs_xmas_house/stol_pc_by_slavon.mdl
models/cs_xmas_house/scar_nighttable_right.mdl
models/cs_xmas_house/scar_nighttable_left.mdl
sound/cs_xmas_house/homealone.wav
sprites/cs_xmas_house/homealone.spr
models/cs_xmas_house/picture_frame_4.mdl
models/cs_xmas_house/picture_frame_5.mdl
models/cs_xmas_house/xmas_kreslo01.mdl
models/cs_xmas_house/xmas_fish.mdl
models/cs_xmas_house/xmas_kurachka.mdl
sprites/glow01.spr
models/cs_xmas_house/mailbox01.mdl
models/cs_xmas_house/xmas_snowder.mdl
models/cs_xmas_house/xmas_kustik.mdl
models/cs_xmas_house/barricade01.mdl
sound/cs_xmas_house/grass.wav
models/cs_xmas_house/xmas_sign01.mdl
sound/cs_xmas_house/wind_ambience8.wav
sound/cs_xmas_house/vehicle4.wav
sound/cs_xmas_house/tankidle1.wav
sound/cs_xmas_house/brendalee.wav
models/cs_xmas_house/xmas_boomb.mdl
models/cs_xmas_house/computer_mouse.mdl
models/cs_xmas_house/computer_mouse2.mdl
models/cs_xmas_house/xmas_krovatishe.mdl
models/3dm_hossie02.mdl
models/dm_hossie01.mdl
models/cs_xmas_house/hessi_bank.mdl
sound/cs_xmas_house/doormove7.wav
sprites/cs_xmas_house/rk_steam.spr
models/dm_hossie03.mdl
sound/cs_xmas_house/policepizdeg.wav
models/dm_hossie04.mdl
overviews/cs_xmas_house.bmp
overviews/cs_xmas_house.txt
