models/de_immortals/hessi_zypresse.mdl
models/de_immortals/skla_tree04.mdl
models/de_immortals/tree_noleaves.mdl
models/de_immortals/zp_tree01.mdl
sprites/de_immortals/scudgo.spr
sprites/de_immortals/skeleton1.spr
sprites/de_immortals/skeleton5.spr
sprites/de_immortals/nmh_hitch3.spr
sound/de_immortals/ambience.wav
sound/de_immortals/ghost.wav
sound/de_immortals/ghost2.wav
sound/de_immortals/scream.wav
sound/de_immortals/scream2.wav
sound/de_immortals/start.wav