decals.wad
halflife.wad
del_this.wad
gfx/env/snowup.tga
gfx/env/snowdn.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowft.tga
gfx/env/snowbk.tga
models/metalplategibs_green.mdl
models/smann.mdl
sprites/glow04.spr
models/wbaum.mdl
models/gesch1.mdl
models/gesch2.mdl
maps/de_xmasdust.bsp
maps/de_xmasdust.txt
overviews/de_xmasdust.bmp
overviews/de_xmasdust.txt