// fy_xmas_amphitheatrum
gfx/detail/dt_brick.tga
gfx/detail/dt_carpet1.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_fabric1.tga
gfx/detail/dt_fabric2.tga
gfx/detail/dt_grass1.tga
gfx/detail/dt_ground1.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_ground4.tga
gfx/detail/dt_ground5.tga
gfx/detail/dt_leather1.tga
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_plaster1.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_rock1.tga
gfx/detail/dt_rough.tga
gfx/detail/dt_smooth1.tga
gfx/detail/dt_smooth2.tga
gfx/detail/dt_snow1.tga
gfx/detail/dt_snow2.tga
gfx/detail/dt_snow.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_stone1.tga
gfx/detail/dt_stone2.tga
gfx/detail/dt_stone3.tga
gfx/detail/dt_stone4.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_wood2.tga
gfx/detail/dt_wood3.tga
gfx/detail/dt_wood.tga
maps/fy_xmas_amphitheatrum.nav
maps/fy_xmas_amphitheatrum.txt
maps/fy_xmas_amphitheatrum_detail.txt
maps/fy_xmas_amphitheatrum.res
overviews/fy_amphitheatrum.bmp
overviews/fy_xmas_amphitheatrum.txt
sound/xmas/JingleBells.wav
sound/xmas/S_leghkim_parom.wav
