// C:\Users\Nouha\Desktop\cstrike\maps\skull_war_chess_2001.res - created with RESGen v1.10
// RESGen is made by Jeroen "ShadowLord" Bogers
// URL: http://www.unitedadmins.com/mapRESGEN.asp
// E-MAIL: resgen@hltools.com
// Res creation date, GMT timezone (dd-mm-yyyy): 08-09-2023

// .res entries:
halflife.wad
chateau.wad
cs_havana.wad
cs_747.wad
cs_bdog.wad
cs_cbble.wad
cstrike.wad
skull_war_chess_2001.wad
gfx/env/winxp2up.tga
gfx/env/winxp2dn.tga
gfx/env/winxp2lf.tga
gfx/env/winxp2rt.tga
gfx/env/winxp2ft.tga
gfx/env/winxp2bk.tga
models/skull_war_chess_2001/sword1.mdl
models/skull_war_chess_2001/knight1.mdl
models/skull_war_chess_2001/mayhem_skull.mdl
models/skull_war_chess_2001/shoppingcart.mdl
models/skull_war_chess_2001/creep_skull1.mdl
models/skull_war_chess_2001/n_m3skeleton.mdl
models/skull_war_chess_2001/mtk_mx5001.mdl
models/skull_war_chess_2001/bskull_template2.mdl
models/skull_war_chess_2001/9ball.mdl
models/skull_war_chess_2001/banka2.mdl
models/player/gsg9/gsg9.mdl
sprites/skull_war_chess_2001/glow02.spr
sprites/skull_war_chess_2001/e-tele1.spr
sprites/laserbeam.spr
models/skull_war_chess_2001/gusano3.mdl
models/skull_war_chess_2001/moyai2.mdl
models/skull_war_chess_2001/skull_gold2.mdl
models/skull_war_chess_2001/bomb3.mdl
models/skull_war_chess_2001/8ball_hard2.mdl
models/skull_war_chess_2001/3atuhy.mdl
models/skull_war_chess_2001/c.mdl
models/skull_war_chess_2001/apex.mdl
models/skull_war_chess_2001/messerschmitt_tail.mdl
models/skull_war_chess_2001/stuka_sc1400.mdl
models/skull_war_chess_2001/nm_magic.mdl
models/skull_war_chess_2001/w_controlpoint3.mdl
models/skull_war_chess_2001/w_controlpoint4.mdl
models/skull_war_chess_2001/w_resupply.mdl
models/skull_war_chess_2001/capsule.mdl
models/skull_war_chess_2001/art1.mdl
models/skull_war_chess_2001/n_badassgman.mdl
models/skull_war_chess_2001/crystal.mdl
models/skull_war_chess_2001/pionblanc2.mdl
models/skull_war_chess_2001/tourblanc4.mdl
models/skull_war_chess_2001/cavalier5.mdl
models/skull_war_chess_2001/pion5.mdl
models/skull_war_chess_2001/foublanc2.mdl
models/skull_war_chess_2001/bg_crystal05.mdl
sprites/skull_war_chess_2001/shine.spr
models/skull_war_chess_2001/steerskull.mdl
sound/skull_war_chess_2001/smoke.wav
sound/skull_war_chess_2001/bad-to-the-bone.wav
sound/skull_war_chess_2001/castle-vein.wav
sound/skull_war_chess_2001/chill_bill.wav
sound/skull_war_chess_2001/robert.wav
sound/skull_war_chess_2001/hard.wav
sound/skull_war_chess_2001/green.wav
sound/skull_war_chess_2001/trance.wav
sound/skull_war_chess_2001/shopping.wav
sound/skull_war_chess_2001/pa_birdloop.wav
sound/skull_war_chess_2001/lava1.wav
sound/skull_war_chess_2001/credits.wav
sound/skull_war_chess_2001/jump.wav
sound/skull_war_chess_2001/cancel_jump.wav
sound/skull_war_chess_2001/rocket.wav
sound/skull_war_chess_2001/danger_alarm.wav
sound/skull_war_chess_2001/samsung_notification.wav
sound/skull_war_chess_2001/goffy_piano.wav
sound/skull_war_chess_2001/drom.wav
sound/skull_war_chess_2001/goffy_sound.wav
sound/skull_war_chess_2001/scar.wav
models/player/guerilla/guerilla.mdl
